export enum Region {
  Adygea,
  Altai,
  Arkhyz,
  Baikal,
  Sibir,
  DalniVostok,
  Kavkaz,
  Kamchatka,
  Kolsky,
  PlatoPutorano,
  Kurily,
  Ural,
  Karelia,
  Solovki,
  Khabarovsk,
  Sakhalin,
}

// [
//   'Белое море',
//   'Восхождение на Казбек',
//   'Восхождение на Эльбрус',
//   'Дагестан',
//   'Ингушетия',
//   'Кабардино-Балкария',
//   'Казань',
//   'Калининград',
//   'Карачаево-Черкесия',
//   'Плато Путорана',
//   'Подмосковье',
//   'Приэльбрусье',
//   'Русский Север',
//   'Северная Осетия',
//   'Северо-Запад (Ленобласть и Карелия)',
//   'Селигер',
//   'Сочи',
//   'Хибины',
//   'Центральный регион',
//   'Чукотка',
//   'Юг России',
// ];

export const regions = [
  { value: Region.Adygea, name: 'Адыгея' },
  { value: Region.Altai, name: 'Алтай' },
  { value: Region.Arkhyz, name: 'Архыз' },
  { value: Region.Baikal, name: 'Байкал' },
  { value: Region.Adygea, name: 'Адыгея' },
  { value: Region.Sibir, name: 'Сибирь' },
  { value: Region.DalniVostok, name: 'Дальний восток' },
  { value: Region.Kavkaz, name: 'Кавказ' },
  { value: Region.Kamchatka, name: 'Камчатка' },
  { value: Region.Kolsky, name: 'Кольский полуостров' },
  { value: Region.PlatoPutorano, name: 'Плато путорано' },
  { value: Region.Kurily, name: 'Курильские острова' },
  { value: Region.Karelia, name: 'Карелия' },
  { value: Region.Solovki, name: 'Соловки' },
  { value: Region.Khabarovsk, name: 'Хабаровский край' },
];
