version: '3.8'

services:
  api_overtour_ru:
    container_name: api_overtour_ru
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/public/images/:/home/node/app/build/public/images"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - overtour
networks:
  overtour:
    external: true