name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build
        run: |
          npm install
          npm run build

#      - name: Create env file
#        run: |
#          touch /build/.env
#          echo PORT=${{ secrets.PORT }} >> /build/.env
#          echo HOST=${{ secrets.HOST }} >> /build/.env
#          cat /build/.env

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          strip_components: 1
          target: ${{ secrets.REMOTE_TARGET }}
          source: "build/"
          rm: true

      - name: Run install on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: ${{ secrets.COMMAND }}
