name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run install on server
        uses: D3rHase/ssh-command-action@{version}
        with:
          HOST: ${{ secrets.REMOTE_HOST }}
          USER: ${{ secrets.REMOTE_USER }}
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          COMMAND: ${{ secrets.COMMAND }}
