name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          cat .env

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          strip_components: 1
          target: ${{ secrets.REMOTE_TARGET }}
          source: "build/"
          rm: true

      - name: Run install on server
        uses: fifsky/ssh-action@master
        with:
          command: ${{ secrets.COMMAND }}
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          pass: ${{ secrets.REMOTE_PASSWORD }}
